package com.emikhalets.core

const val UNDEFINED_ID = -1
const val EMPTY_STRING = ""

const val DEFAULT_CATEGORY_INCOME_ID = -2L
const val DEFAULT_CATEGORY_EXPENSE_ID = -3L
const val DEFAULT_WALLET_ID = -2L
const val DEFAULT_CURRENCY_ID = -2L

const val CODE_DELETE_CURRENCY_WITH_TRANSACTIONS = 1000
const val CODE_CATEGORY_EXISTED = 1001
const val CODE_CURRENCY_EXISTED = 1002
const val CODE_WALLET_EXISTED = 1003